"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { medicalApi } from "@/lib/medical-api";
import { LoaderCircle } from "lucide-react";
type Preview = {name: string; images: {label: string; src: string}[]; text?: string; coverage?: string[]; waveforms?: number[][]; error?: string};
export function SourcePreviews({files, fileIds, onUploaded, onBusy}: {files: File[]; fileIds: string[]; onUploaded: (ids: string[]) => void; onBusy: (busy: boolean) => void}) {
 const [previews,setPreviews]=useState<Preview[]>([]);
 const [loading,setLoading]=useState(true);
 useEffect(() => {
  let alive=true;
  async function load() {
   onBusy(true);
   const ids: string[]=[];const items:Preview[]=[];
   try {
    if (files.length) {
     for (const file of files) {
      if (!alive) return;
      const form=new FormData();form.set("file",file);
      try {const uploaded=await medicalApi("v1/files",{method:"POST",body:form});ids.push(uploaded.id);items.push(await medicalApi(`v1/files/${uploaded.id}/preview`));}
      catch(error){items.push({name:file.name,images:[],error:error instanceof Error ? error.message : "Preview unavailable."});}
      if(alive)setPreviews([...items]);
     }
     if(alive)onUploaded(ids);
    } else {
     for(const id of fileIds){try {items.push(await medicalApi(`v1/files/${id}/preview`));}catch(error){items.push({name:"Source preview",images:[],error:error instanceof Error ? error.message : "Preview unavailable."});}}
     if(alive)setPreviews(items);
    }
   } finally {if(alive){setLoading(false);onBusy(false);}}
  }
  void load();
  return () => {alive=false;};
 },[files,fileIds,onUploaded,onBusy]);
 if(!previews.length && !loading)return null;
 return <section className="source-previews"><h2>Source previews</h2>{loading && <p className="input-help"><LoaderCircle size={14} className="animate-spin"/>Preparing previews…</p>}{previews.map((preview,index)=><article key={index} className="source-preview"><h3>{preview.name}</h3>{preview.error && <p className="medical-error">{preview.error}</p>}<div className="preview-images">{preview.images.map((image,i)=><figure key={i}>{/* Local preview data URLs are generated by the authenticated Python API. */}<Image src={image.src} alt={image.label} width={768} height={768} unoptimized/><figcaption>{image.label.replace(/^preview: /,"")}</figcaption></figure>)}</div>{preview.waveforms && <div className="waveform-previews">{preview.waveforms.map((values,i)=>{const min=Math.min(...values),max=Math.max(...values);const points=values.map((v,x)=>`${x*300/(values.length-1)},${55-(v-min)/Math.max(max-min,.00001)*45}`).join(" ");return <figure key={i}><figcaption>Channel {i+1}</figcaption><svg viewBox="0 0 300 60" role="img" aria-label={`ECG channel ${i+1}, normalized display`}><polyline points={points} fill="none" stroke="currentColor" strokeWidth="1.2"/></svg></figure>;})}</div>}{preview.text && <details open={!preview.images.length}><summary>Source text</summary><pre>{preview.text}</pre></details>}{preview.coverage?.map((note,i)=><p className="input-help" key={i}>{note}</p>)}</article>)}</section>;
}
